import { z } from 'zod';
import { createScorer } from '@mastra/core/evals';
import { getAssistantMessageFromRunOutput } from '@mastra/evals/scorers/utils';

/**
 * Extracts text from scorer output, handling both:
 * - Agent-formatted output (MastraDBMessage[]) when used as an agent scorer
 * - Simple { text: string } when called manually from workflows
 */
function extractOutputText(output: unknown): string {
  if (Array.isArray(output)) {
    return getAssistantMessageFromRunOutput(output) ?? '';
  }
  if (typeof output === 'string') return output;
  if (output && typeof output === 'object' && 'text' in output) {
    return (output as { text: string }).text;
  }
  return '';
}

const BASED_INSTRUCTIONS = `You are a cultural critic and vibe evaluator. Your job is to judge how "based" a piece of writing is.

"Based" means the content is real, authentic, unapologetic, bold, and says what needs to be said without corporate fluff or hand-wringing. Based content has conviction, edge, and personality. It doesn't hedge every statement or pad itself with meaningless qualifiers.

The opposite of based is mid, bland, soulless, overly-safe corporate slop that says nothing and offends no one because it commits to nothing.`;

export const basedScorer = createScorer({
  id: 'based-scorer',
  name: 'Based',
  description: 'Scores blog post output from 0 to 10 on how based (real, dope, badass) it is',
  judge: {
    model: 'openai/gpt-5.3-codex',
    instructions: BASED_INSTRUCTIONS,
  },
})
  .analyze({
    description: 'Analyze the content for based-ness across multiple dimensions',
    outputSchema: z.object({
      authenticity: z.number().min(0).max(10).describe('How real and genuine vs. corporate and formulaic'),
      boldness: z.number().min(0).max(10).describe('How confident and unapologetic vs. hedging and wishy-washy'),
      originality: z.number().min(0).max(10).describe('How fresh and unique vs. recycled and generic'),
      personality: z.number().min(0).max(10).describe('How much voice and character vs. bland and interchangeable'),
      impact: z.number().min(0).max(10).describe('How memorable and hard-hitting vs. forgettable'),
      highlights: z.array(z.string()).describe('The most based lines or ideas in the content'),
      cringe: z.array(z.string()).describe('The most mid or cringe parts that drag the score down'),
    }),
    createPrompt: ({ run }) => {
      const output = extractOutputText(run.output);
      return `Rate the following blog post on how "based" it is. Evaluate across these dimensions, each scored 0-10:

- **Authenticity** (0-10): Does it feel real and genuine, or like it was generated by a corporate content mill? Does it have a point of view?
- **Boldness** (0-10): Does it make strong claims and stand behind them, or does it hedge everything with "it depends" and "some might say"?
- **Originality** (0-10): Does it bring fresh takes or insights, or is it just rehashing the same tired talking points everyone else writes?
- **Personality** (0-10): Does it have voice, humor, or swagger, or could it have been written by any interchangeable content writer?
- **Impact** (0-10): Will the reader remember this tomorrow, or will they forget it the second they close the tab?

Also identify:
- The most based highlights (lines or ideas that go hard)
- The most cringe/mid parts (lines that are generic, fluffy, or soul-draining)

Content to evaluate:
"""
${output}
"""`;
    },
  })
  .generateScore(({ results }) => {
    const { authenticity, boldness, originality, personality, impact } =
      results.analyzeStepResult;
    // Weighted average favoring boldness and authenticity
    const raw =
      authenticity * 0.25 +
      boldness * 0.25 +
      originality * 0.2 +
      personality * 0.2 +
      impact * 0.1;
    return Math.round(raw * 10) / 10;
  })
  .generateReason({
    description: 'Generate a reason explaining the based score',
    createPrompt: ({ results, score }) => {
      const { authenticity, boldness, originality, personality, impact, highlights, cringe } =
        results.analyzeStepResult;
      return `Summarize why this blog post scored ${score}/10 on the based scale.

Dimension scores:
- Authenticity: ${authenticity}/10
- Boldness: ${boldness}/10
- Originality: ${originality}/10
- Personality: ${personality}/10
- Impact: ${impact}/10

Most based parts: ${highlights.length > 0 ? highlights.join(' | ') : 'None stood out'}
Most mid/cringe parts: ${cringe.length > 0 ? cringe.join(' | ') : 'Nothing too cringe'}

Write a short, punchy 2-3 sentence verdict on how based this content is. Be honest and direct - that's what being based is all about.`;
    },
  });
